import { useEffect, useState } from 'react';
import { Leaf } from 'lucide-react';
import HeroSection from './components/HeroSection';
import AnalysisPanel from './components/AnalysisPanel';
import HistorySection from './components/HistorySection';
import StatsBar from './components/StatsBar';
import PredictionResult from './components/PredictionResult';
import { supabase } from './lib/supabase';
import type { Prediction } from './lib/supabase';

export default function App() {
  const [history, setHistory] = useState<Prediction[]>([]);
  const [selectedHistory, setSelectedHistory] = useState<Prediction | null>(null);
  const [loadingHistory, setLoadingHistory] = useState(true);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    setLoadingHistory(true);
    const { data } = await supabase
      .from('predictions')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);
    if (data) setHistory(data);
    setLoadingHistory(false);
  };

  const handleNewPrediction = (prediction: Prediction) => {
    setHistory(prev => [prediction, ...prev]);
  };

  const handleDeletePrediction = async (id: string) => {
    await supabase.from('predictions').delete().eq('id', id);
    setHistory(prev => prev.filter(p => p.id !== id));
    if (selectedHistory?.id === id) setSelectedHistory(null);
  };

  const handleClearAll = async () => {
    await supabase.from('predictions').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    setHistory([]);
    setSelectedHistory(null);
  };

  const generateReportContent = (p: Prediction) => {
    const lines = [
      '═══════════════════════════════════════════════════',
      '       CROP DISEASE DETECTION SYSTEM - REPORT      ',
      '═══════════════════════════════════════════════════',
      '',
      `Date: ${new Date(p.created_at).toLocaleString()}`,
      `Report ID: ${p.id}`,
      '',
      '───────────────────────────────────────────────────',
      'DIAGNOSIS SUMMARY',
      '───────────────────────────────────────────────────',
      `Disease: ${p.disease_name}`,
      `Crop Type: ${p.crop_type}`,
      `Status: ${p.is_healthy ? 'HEALTHY' : 'DISEASED'}`,
      `Confidence: ${p.confidence}%`,
      '',
      '───────────────────────────────────────────────────',
      'DESCRIPTION',
      '───────────────────────────────────────────────────',
      p.description,
      '',
    ];

    if (p.causes.length > 0) {
      lines.push('───────────────────────────────────────────────────', 'CAUSES', '───────────────────────────────────────────────────');
      p.causes.forEach((c, i) => lines.push(`${i + 1}. ${c}`));
      lines.push('');
    }

    lines.push(
      '───────────────────────────────────────────────────',
      'PREVENTION METHODS',
      '───────────────────────────────────────────────────'
    );
    p.prevention.forEach((pv, i) => lines.push(`${i + 1}. ${pv}`));
    lines.push(
      '',
      '───────────────────────────────────────────────────',
      'RECOMMENDED TREATMENT',
      '───────────────────────────────────────────────────',
      p.treatment,
      '',
      '═══════════════════════════════════════════════════',
      'Generated by Crop Disease Detection System',
      '═══════════════════════════════════════════════════'
    );
    return lines.join('\n');
  };

  const downloadReport = (p: Prediction) => {
    const blob = new Blob([generateReportContent(p)], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disease-report-${p.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <HeroSection />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <StatsBar predictions={history} />

        <div className="mt-8 grid grid-cols-1 lg:grid-cols-5 gap-6">
          <div className="lg:col-span-3">
            <AnalysisPanel onNewPrediction={handleNewPrediction} downloadReport={downloadReport} />
          </div>

          <div className="lg:col-span-2 space-y-6">
            {loadingHistory ? (
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8 text-center">
                <div className="w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin mx-auto mb-3" />
                <p className="text-sm text-gray-400">Loading history...</p>
              </div>
            ) : (
              <HistorySection
                history={history}
                onSelect={setSelectedHistory}
                onDelete={handleDeletePrediction}
                onClearAll={handleClearAll}
                selectedId={selectedHistory?.id}
              />
            )}

            {selectedHistory && (
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <div className="w-1 h-5 bg-emerald-500 rounded-full" />
                  <h3 className="font-semibold text-gray-700 text-sm">Selected Record Details</h3>
                </div>
                <PredictionResult
                  prediction={selectedHistory}
                  onDownloadReport={() => downloadReport(selectedHistory)}
                />
              </div>
            )}
          </div>
        </div>
      </main>

      <footer className="border-t border-gray-100 bg-white mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center">
                <Leaf className="w-4 h-4 text-white" />
              </div>
              <span className="font-bold text-gray-800 text-sm">Crop Disease Detection System</span>
            </div>
            <p className="text-xs text-gray-400">AI-powered plant pathology using CNN deep learning • PlantVillage dataset</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
